version: '3.3'
services:
  ecom:
    container_name: ecom
    image: postgres:12.8
    restart: always
    environment:
      - POSTGRES_USER=pg
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=ecom
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db: